-- Audit log for sensitive operations (transfers, deletions, etc.)
-- Records: who (user_id), what (action), when, and relevant details (JSON).
-- Uses a separate table so it doesn't interfere with transaction performance.
-- details is TEXT: portable across H2 and PostgreSQL (CLOB works on H2 only).

CREATE TABLE tb_audit_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action              VARCHAR(50) NOT NULL,          -- e.g. 'TRANSFER', 'DELETE_USER', 'CREATE_TRANSACTION'
    actor_user_id       BIGINT,                        -- who performed the action (nullable for system actions)
    actor_name          VARCHAR(255),                  -- cached name for readability
    target_entity       VARCHAR(50),                   -- e.g. 'tb_transaction', 'tb_user'
    target_id           BIGINT,                        -- primary key of affected entity
    details             TEXT,                          -- flexible payload (JSON as text)
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_log_actor ON tb_audit_log (actor_user_id);
CREATE INDEX idx_audit_log_target ON tb_audit_log (target_entity, target_id);
CREATE INDEX idx_audit_log_created ON tb_audit_log (created_at);