-- Login users (credentials), separate from the banking User aggregate.
-- The banking User (tb_user) has account/card/features/news; credentials live
-- here to avoid overloading that aggregate with password concerns.
-- A banking user can have a matching auth user (same username == user.id) so
-- the authenticated actor maps back to the domain entity for created_by/audit.

CREATE TABLE tb_auth_user (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(20)  NOT NULL DEFAULT 'USER',
    user_id    BIGINT,                              -- links to tb_user.id when the actor is a banking user
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed: the protected user (id 1, "Devweekerson") gets an admin login so the
-- API is usable out of the box. Password "admin123" (bcrypt hash below).
INSERT INTO tb_auth_user (username, password, role, user_id) VALUES (
    'devweekerson',
    '$2a$10$0zwEwh4T9a74guEXVOMwg.ki1zurnK88iQusuIX1b0QJgnihW2/T.',
    'ADMIN',
    1
);
