-- Rotating refresh tokens for JWT sessions. The token itself is opaque and
-- stored hashed (SHA-256); a refresh rotates the token (old one revoked) and
-- logout revokes it. One refresh token per session row.

CREATE TABLE tb_refresh_token (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id  BIGINT NOT NULL,
    token_hash    VARCHAR(64) NOT NULL UNIQUE,       -- SHA-256 hex of the opaque token
    expires_at    TIMESTAMP NOT NULL,
    revoked       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tb_refresh_token_auth_user FOREIGN KEY (auth_user_id) REFERENCES tb_auth_user (id)
);

CREATE INDEX idx_refresh_token_auth_user ON tb_refresh_token (auth_user_id);
