-- Schema for the Santander Dev Week API (User + Account + Card + Feature + News).
-- Mirrors the JPA mapping exactly so `ddl-auto: validate` passes on H2 and PostgreSQL.

CREATE TABLE tb_account (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number           VARCHAR(255) UNIQUE,
    agency           VARCHAR(255),
    balance          NUMERIC(13, 2),
    additional_limit NUMERIC(13, 2)
);

CREATE TABLE tb_card (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number          VARCHAR(255) UNIQUE,
    available_limit NUMERIC(13, 2)
);

-- @OneToOne join columns (account_id / card_id) live on the owning side (tb_user).
CREATE TABLE tb_user (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    account_id BIGINT,
    card_id    BIGINT,
    CONSTRAINT fk_tb_user_account FOREIGN KEY (account_id) REFERENCES tb_account (id),
    CONSTRAINT fk_tb_user_card    FOREIGN KEY (card_id)    REFERENCES tb_card (id),
    CONSTRAINT uq_tb_user_account UNIQUE (account_id),
    CONSTRAINT uq_tb_user_card    UNIQUE (card_id)
);

CREATE TABLE tb_feature (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon        VARCHAR(255),
    description VARCHAR(255)
);

CREATE TABLE tb_news (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon        VARCHAR(255),
    description VARCHAR(255)
);

-- Join tables created by the explicit @JoinTable on User.features / User.news,
-- carrying the @OrderColumn index so the lists keep their order.
CREATE TABLE tb_user_features (
    user_id       BIGINT NOT NULL,
    features_id   BIGINT NOT NULL,
    features_order INTEGER,
    CONSTRAINT fk_tb_user_features_user    FOREIGN KEY (user_id)    REFERENCES tb_user (id),
    CONSTRAINT fk_tb_user_features_feature FOREIGN KEY (features_id) REFERENCES tb_feature (id),
    CONSTRAINT uq_tb_user_features_features UNIQUE (features_id)
);

CREATE TABLE tb_user_news (
    user_id    BIGINT NOT NULL,
    news_id    BIGINT NOT NULL,
    news_order INTEGER,
    CONSTRAINT fk_tb_user_news_user FOREIGN KEY (user_id) REFERENCES tb_user (id),
    CONSTRAINT fk_tb_user_news_news FOREIGN KEY (news_id) REFERENCES tb_news (id),
    CONSTRAINT uq_tb_user_news_news UNIQUE (news_id)
);
