-- Statement/transaction table for the account. The FK lives here (owning side),
-- mirroring how tb_user owns the account_id FK. Mirrors the JPA mapping exactly
-- so `ddl-auto: validate` passes on H2 and PostgreSQL.

CREATE TABLE tb_transaction (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id             BIGINT NOT NULL,
    destination_account_id BIGINT,
    type                   VARCHAR(255) NOT NULL,
    amount                 NUMERIC(13, 2) NOT NULL,
    created_at             TIMESTAMP NOT NULL,
    CONSTRAINT fk_tb_transaction_account FOREIGN KEY (account_id) REFERENCES tb_account (id),
    CONSTRAINT ck_tb_transaction_amount_positive CHECK (amount > 0)
);
